/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'interviewed' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'offered' : null };
export interface Company {
  'id' : bigint,
  'name' : string,
  'location' : string,
  'industry' : string,
}
export interface JobApplication {
  'status' : ApplicationStatus,
  'submittedTime' : Time,
  'studentId' : Principal,
  'jobId' : bigint,
  'jobTitle' : string,
  'companyName' : string,
}
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'minCGPA' : number,
  'postedTime' : Time,
  'description' : string,
  'logoUrl' : [] | [string],
  'eligibleBranches' : Array<string>,
  'salaryRange' : [bigint, bigint],
  'requiredSkills' : Array<string>,
  'companyId' : bigint,
}
export interface StudentProfile {
  'bio' : string,
  'principal' : Principal,
  'cgpa' : number,
  'name' : string,
  'email' : string,
  'resumeLink' : string,
  'branches' : Array<string>,
  'skills' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'cgpa' : number,
  'name' : string,
  'email' : string,
  'resumeLink' : string,
  'branches' : Array<string>,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCompany' : ActorMethod<[string, string, string], bigint>,
  'addJobPosting' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<string>,
      number,
      Array<string>,
      [bigint, bigint],
      [] | [string],
    ],
    bigint
  >,
  'applyForJob' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStudentProfile' : ActorMethod<
    [string, string, number, Array<string>, Array<string>, string, string],
    undefined
  >,
  'getAppliedJobs' : ActorMethod<[], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanies' : ActorMethod<[], Array<Company>>,
  'getJobApplication' : ActorMethod<[Principal, bigint], [] | [JobApplication]>,
  'getJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getJobPostingsByCompany' : ActorMethod<[bigint], Array<JobPosting>>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [Principal, bigint, ApplicationStatus],
    undefined
  >,
  'updateStudentProfile' : ActorMethod<
    [string, string, number, Array<string>, Array<string>, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];