/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'interviewed' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'offered' : IDL.Null,
});
export const Time = IDL.Int;
export const JobApplication = IDL.Record({
  'status' : ApplicationStatus,
  'submittedTime' : Time,
  'studentId' : IDL.Principal,
  'jobId' : IDL.Nat,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'cgpa' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'resumeLink' : IDL.Text,
  'branches' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const Company = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'location' : IDL.Text,
  'industry' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'minCGPA' : IDL.Float64,
  'postedTime' : Time,
  'description' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'eligibleBranches' : IDL.Vec(IDL.Text),
  'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'requiredSkills' : IDL.Vec(IDL.Text),
  'companyId' : IDL.Nat,
});
export const StudentProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'cgpa' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'resumeLink' : IDL.Text,
  'branches' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCompany' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addJobPosting' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Tuple(IDL.Nat, IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'applyForJob' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStudentProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAppliedJobs' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getJobApplication' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(JobApplication)],
      ['query'],
    ),
  'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getJobPostingsByCompany' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, ApplicationStatus],
      [],
      [],
    ),
  'updateStudentProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'interviewed' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'offered' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobApplication = IDL.Record({
    'status' : ApplicationStatus,
    'submittedTime' : Time,
    'studentId' : IDL.Principal,
    'jobId' : IDL.Nat,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'cgpa' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'resumeLink' : IDL.Text,
    'branches' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const Company = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'location' : IDL.Text,
    'industry' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'minCGPA' : IDL.Float64,
    'postedTime' : Time,
    'description' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'eligibleBranches' : IDL.Vec(IDL.Text),
    'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'requiredSkills' : IDL.Vec(IDL.Text),
    'companyId' : IDL.Nat,
  });
  const StudentProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'cgpa' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'resumeLink' : IDL.Text,
    'branches' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCompany' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addJobPosting' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Tuple(IDL.Nat, IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'applyForJob' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStudentProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAppliedJobs' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getJobApplication' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(JobApplication)],
        ['query'],
      ),
    'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getJobPostingsByCompany' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, ApplicationStatus],
        [],
        [],
      ),
    'updateStudentProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };